### ISSUE TITLE
Building with Thunderbolt support

### ISSUE THREAD

**Issue by HyperLethalVector** [01org/thunderbolt-software-kernel-tree#5]
Hi,

I'm a little new to building kernels.

How do I enable the thunderbolt support in the kernel build process?

Additionally, building the kernel and modules seems to disable my networking, forcing me to boot with the previous kernel.

Any help would be appreciated!

**Comment by ybernat** [comment]
Before going into much details about kernel building (which isn't a simple task), let's make sure if you really need this kernel module, as for some of Thunderbolt functionalities you may have better options than compiling this.
What is that you want to achieve?

**Comment by HyperLethalVector** [comment]
Basically, I have an Intel thunderbolt 3 type-c port which I wish to use with my thunderbolt -> firewire 800 adapter.

Under my windows installation this works like a charm.

My current configuration is as follows:

OS: Ubuntu 16.04 (linux kernal 4.8.0-58 generic)
Computer: MSI GT83VR 

My attempt to build freezes when accessing networking (using ifconfig freezes the terminal)

Sorry if I'm a little vauge!

if there's alternatives to building this please let me know!

**Comment by ybernat** [comment]
Under your Windows installation, did you have to approve the adapter for connection?
My understanding is that this is a Thunderbolt device, and this kernel module will not help in connection it as this module doesn't support device approval.
You can take the new kernel from kernel-next, which includes the new kernel module. The new module does support device approval as described here: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/Documentation/admin-guide/thunderbolt.rst

**Comment by michael-jamet** [comment]
Alternatively you can try to change default BIOS Thunderbolt security Level to be legacy. This will remove Thunderbolt security (that we always recommend) not supported in this specific kernel version of Ubuntu. You should be then able to access the device but not securely.
